name: snowball_sdk_ads
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  applovin_max: ^4.2.0
  firebase_analytics: ^11.4.0
  firebase_remote_config: ^5.3.0
  google_mobile_ads: ^5.2.0
  uuid: ^4.5.1
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.snowball.snowball_sdk_ads
        pluginClass: SnowballSdkAdsPlugin
      ios:
        pluginClass: SnowballSdkAdsPlugin
